### ISSUE TITLE
Disable a configuration (but keeps its value)

### ISSUE THREAD

**Issue by erikryverling** [iZettle/wrench#45]
String backed properties could be cumbersome to type over and over when you want to to tests your app with and without the configuration property set.

It would be great if you could have a _Disable_ button that disables the property, but keeps the entered value, in conjunction with the current _Revert_  button which disables the property and clears it's value.

**Comment by erikeelde** [comment]
I would rather introduce an autocomplete for configurations - which would simplify readding historic values to a configuration. I'll look into it.
