### ISSUE TITLE
Add info on how to build it

### ISSUE THREAD

**Issue by joezorry** [iZettle/wrench#8]
After checking it out I get these errors,
which should probably be inserted in the readme on how to take care of building.

I can probably navigate through it, but not everyone knows how.

![screen shot 2017-02-24 at 17 04 44](https://cloud.githubusercontent.com/assets/315692/23310695/ad601078-fab3-11e6-8ccc-0f0442c91310.png)

**Comment by erikeelde** [comment]
@joezorry since we've removed any and all logging / crashreporting I'll close this.
